<?php

const NETCAT_MODULE_BANNER_DESCRIPTION = 'Extended banner ad manager.';

const NETCAT_MODULE_BANNER_MAINSTATS = 'Summary statistics';
const NETCAT_MODULE_BANNER_BANNER = 'Banner';
const NETCAT_MODULE_BANNER_BANNERS = 'Banners';
const NETCAT_MODULE_BANNER_ZONE = 'Zone';
const NETCAT_MODULE_BANNER_ZONES = 'Zones';
const NETCAT_MODULE_BANNER_CAMPAIGN = 'Campaign';
const NETCAT_MODULE_BANNER_CAMPAIGNS = 'Campaigns';
const NETCAT_MODULE_BANNER_PAGE = 'Page';
const NETCAT_MODULE_BANNER_PAGES = 'Pages';
const NETCAT_MODULE_BANNER_BTT_SHOW = 'Show';
const NETCAT_MODULE_BANNER_PERFROM = 'per period from';
const NETCAT_MODULE_BANNER_PERTO = 'till';

const NETCAT_MODULE_BANNER_TODAY = 'today';
const NETCAT_MODULE_BANNER_YESTERDAY = 'yesterday';
const NETCAT_MODULE_BANNER_WEEK = 'week';
const NETCAT_MODULE_BANNER_MONTH = 'month';
const NETCAT_MODULE_BANNER_ALLPERIOD = 'all period';

const NETCAT_MODULE_BANNER_HOUR = 'Hour';
const NETCAT_MODULE_BANNER_SHOWS = 'Shows';
const NETCAT_MODULE_BANNER_CLICKS = 'Clicks';
const NETCAT_MODULE_BANNER_CTR = 'CTR';
const NETCAT_MODULE_BANNER_CTRP = 'CTR, %';
const NETCAT_MODULE_BANNER_TOTAL = 'Total';
const NETCAT_MODULE_BANNER_COUNT = 'Count';
const NETCAT_MODULE_BANNER_ACTIVE = 'Active';

const NETCAT_MODULE_BANNER_MSG_AVGCLICKSCOUNTPERPERIOD = 'Average number of shows and clicks per period';
const NETCAT_MODULE_BANNER_MSG_CLICKSCOUNTPERPERIOD = 'Number of shows and clicks per period';

const NETCAT_MODULE_BANNER_SETUP_BANNERS = 'Banners';
const NETCAT_MODULE_BANNER_SETUP_SCRIPTS = 'Scripts';
const NETCAT_MODULE_BANNER_SETUP_EXCLUSION = 'Exclusion';
const NETCAT_MODULE_BANNER_SETUP_ZONES = 'Zones';
const NETCAT_MODULE_BANNER_SETUP_CAMPAIGN = 'Campaign';

const NETCAT_MODULE_BANNER_SETUP = 'Setup';
const NETCAT_MODULE_BANNER_EXCEL_EXPORT = 'Export in Excel';
?>