<?php

// main
const NETCAT_MODULE_COMMENTS_GUEST = 'Guest';
const NETCAT_MODULE_COMMENTS_DESCRIPTION = 'This module is for the organization of comments.';
// links
const NETCAT_MODULE_COMMENTS_LINK_REPLY = 'Reply';
const NETCAT_MODULE_COMMENTS_LINK_EDIT = 'Edit';
const NETCAT_MODULE_COMMENTS_LINK_DELETE = 'Delete';
const NETCAT_MODULE_COMMENTS_LINK_COMMENT = 'Comment';
const NETCAT_MODULE_COMMENTS_SUBSCRIBE_TO_ALL = 'Subscribe';
const NETCAT_MODULE_COMMENTS_UNSUBSCRIBE_FROM_ALL = 'Unsubscribe';
const NETCAT_MODULE_COMMENTS_LINK_AUTH = 'Sign in';
const NETCAT_MODULE_COMMENTS_MODERATOR_CLOSE = 'Deny comments';
const NETCAT_MODULE_COMMENTS_MODERATOR_OPEN = 'Allow comments';
const NETCAT_MODULE_COMMENTS_RATING_NOTIFY = 'Your vote has been counted';

const NETCAT_MODULE_COMMENTS_ADD_FORM_DELETE_QUESTION = 'Delete this comment?';

// errors
const NETCAT_MODULE_COMMENTS_NO_ACCESS = 'No permission to complete this operation!';
const NETCAT_MODULE_COMMENTS_UNCORRECT_DATA = 'Uncorrect data format!';

const NETCAT_MODULE_COMMENTS_ADD_FORM_ADD_BUTTON = 'Add';
const NETCAT_MODULE_COMMENTS_ADD_FORM_SUBSCRIBE_BUTTON = 'Subscribe';
const NETCAT_MODULE_COMMENTS_ADD_FORM_APPEND_BUTTON = 'Save';
const NETCAT_MODULE_COMMENTS_ADD_FORM_UPDATE_BUTTON = 'Update';
const NETCAT_MODULE_COMMENTS_ADD_FORM_DELETE_BUTTON = 'Delete';
const NETCAT_MODULE_COMMENTS_ADD_FORM_CANCEL_BUTTON = 'Cancel';
const NETCAT_MODULE_COMMENTS_ADD_FORM_LOADING_TEXT = 'Loading data...';

// admin interface
const NETCAT_MODULE_COMMENTS_ADMIN_MAINSETTINGS_SAVE_BUTTON = 'Save';

//tabs
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_LIST_TAB = 'Comments list';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_TEMPLATE_TAB = 'Template settings';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_TEMPLATE_MAIN = 'Common settings';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_SUBSCRIBE_TAB = 'Subscriptions and notifications';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_CONVERTER_TAB = 'Converter';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_OPTIMIZE_TAB = 'Optimize data';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_SUBSCRIBES = 'Manage subscribes';

//comments list
const NETCAT_MODULE_COMMENTS_ADMIN_CHECK = 'check';
const NETCAT_MODULE_COMMENTS_ADMIN_CHECK_OK = 'Comment has been successfully checked';
const NETCAT_MODULE_COMMENTS_ADMIN_CHECK_COMMENTS_OK = 'Selected comments were checked';
const NETCAT_MODULE_COMMENTS_ADMIN_UNCHECK = 'uncheck';
const NETCAT_MODULE_COMMENTS_ADMIN_UNCHECK_OK = 'Comment has been successfully unchecked';
const NETCAT_MODULE_COMMENTS_ADMIN_UNCHECK_COMMENTS_OK = 'Selected comments were unchecked';
const NETCAT_MODULE_COMMENTS_ADMIN_NO_SELECTED_COMMENTS = 'Comments are not selected';
const NETCAT_MODULE_COMMENTS_ADMIN_EDIT = 'change';
const NETCAT_MODULE_COMMENTS_ADMIN_EDIT_OK = 'Comment has been successfully changed';
const NETCAT_MODULE_COMMENTS_ADMIN_DEL_OK = 'Selected comments have been successfully removed';
const NETCAT_MODULE_COMMENTS_ADMIN_DEL_ALL_OK = 'All comments have been successfully removed';
const NETCAT_MODULE_COMMENTS_ADMIN_DEL_BACK = 'Return';

//filter
const NETCAT_MODULE_COMMENTS_ADMIN_COMMENTS_LIST_SELECT = 'Fetch comments';
const NETCAT_MODULE_COMMENTS_ADMIN_COMMENTS_SUBSCRIBES_SELECT = 'Fetch subscribes';
const NETCAT_MODULE_COMMENTS_ADMIN_NO_COMMENTS = 'No comments';
const NETCAT_MODULE_COMMENTS_ADMIN_NO_SUBSCRIBES = 'No subscribes';
const NETCAT_MODULE_COMMENTS_ADMIN_ESSENCE = 'Essence';
const NETCAT_MODULE_COMMENTS_ADMIN_USER = 'User';
const NETCAT_MODULE_COMMENTS_ADMIN_CATALOGUE = 'Site';
const NETCAT_MODULE_COMMENTS_ADMIN_SUBDIVISION = 'Subdivision';
const NETCAT_MODULE_COMMENTS_ADMIN_CC = 'Subclass';
const NETCAT_MODULE_COMMENTS_ADMIN_MESSAGE = 'Object';
const NETCAT_MODULE_COMMENTS_ADMIN_NONE_CC = 'no subclasses';
const NETCAT_MODULE_COMMENTS_ADMIN_NONE_SUB = 'no subdivisions';
const NETCAT_MODULE_COMMENTS_ADMIN_NONE_CATALOGUE = 'no sites';
const NETCAT_MODULE_COMMENTS_ADMIN_WHOLESUB = 'with cilds';
const NETCAT_MODULE_COMMENTS_ADMIN_LOAD = '- Load... -';
const NETCAT_MODULE_COMMENTS_ADMIN_CLASS = 'Select component';
const NETCAT_MODULE_COMMENTS_ADMIN_ALLUSERS = 'all';
const NETCAT_MODULE_COMMENTS_ADMIN_ONUSERS = 'checked';
const NETCAT_MODULE_COMMENTS_ADMIN_OFFUSERS = 'unchecked';
const NETCAT_MODULE_COMMENTS_ADMIN_DOGET = 'Select';
const NETCAT_MODULE_COMMENTS_ADMIN_QTY = 'Number per page';
const NETCAT_MODULE_COMMENTS_ADMIN_SUBS_QTY = 'Number of subscribes per page';
const NETCAT_MODULE_COMMENTS_ADMIN_SUBSCRIBERS_USER = 'Subscriber';
const NETCAT_MODULE_COMMENTS_ADMIN_FROM_LIST = 'From list';
const NETCAT_MODULE_COMMENTS_ADMIN_NO_HIERARHY = 'Show subscribes only for picked essence';
const NETCAT_MODULE_COMMENTS_ADMIN_DATE = 'Date';
const NETCAT_MODULE_COMMENTS_ADMIN_DATE_FROM = 'Period from ';
const NETCAT_MODULE_COMMENTS_ADMIN_DATE_TO = ' to ';

const NETCAT_MODULE_COMMENTS_ADMIN_CONFIRM_DEL = 'Confirm delete';
const NETCAT_MODULE_COMMENTS_ADMIN_CONFIRM_DEL_ALL = 'Confirm the deletion of all comments';
const NETCAT_MODULE_COMMENTS_ADMIN_CONFIRM_DEL_OK = 'Confirm';

//edit
const NETCAT_MODULE_COMMENTS_ADMIN_EDIT_TEXT = 'Comment text';
const NETCAT_MODULE_COMMENTS_ADMIN_EDIT_AUTHOR = 'Comment author:';
const NETCAT_MODULE_COMMENTS_ADMIN_EDIT_AUTHOR_USER = 'User:';
const NETCAT_MODULE_COMMENTS_ADMIN_EDIT_AUTHOR_NAME = 'Guest name:';
const NETCAT_MODULE_COMMENTS_ADMIN_EDIT_AUTHOR_EMAIL = 'Guest email:';
const NETCAT_MODULE_COMMENTS_ADMIN_EDIT_SAVE_EMAIL_ERROR = 'Enter the correct email';
const NETCAT_MODULE_COMMENTS_ADMIN_EDIT_SAVE_OK = 'Changes saved.';


//converter
const NETCAT_MODULE_COMMENTS_ADMIN_CONVERTER_RETURN_BUTTON = 'Return';
const NETCAT_MODULE_COMMENTS_ADMIN_CONVERTER_SAVE_BUTTON_4 = 'Select catalogue';
const NETCAT_MODULE_COMMENTS_ADMIN_CONVERTER_SAVE_BUTTON_5 = 'Select subdivision';
const NETCAT_MODULE_COMMENTS_ADMIN_CONVERTER_SAVE_BUTTON_6 = 'Convert';
const NETCAT_MODULE_COMMENTS_ADMIN_CONVERTER_SELECT_CATALOGUE = 'Catalogue';
const NETCAT_MODULE_COMMENTS_ADMIN_CONVERTER_SELECT_SUBDIVISION = 'Subdivision selection';
const NETCAT_MODULE_COMMENTS_ADMIN_CONVERTER_SELECT_SUBCLASS = 'Component selection';
const NETCAT_MODULE_COMMENTS_ADMIN_CONVERTER_DIALOG = 'Select dialog';
const NETCAT_MODULE_COMMENTS_ADMIN_CONVERT_OK = 'Comments converted.';
const NETCAT_MODULE_COMMENTS_ADMIN_CONVERT_ERROR = 'Convertation error.';
const NETCAT_MODULE_COMMENTS_ADMIN_CONVERT_PARENT_ERROR = 'Comments and replies convertation error. Duplicate data into the base.';
const NETCAT_MODULE_COMMENTS_ADMIN_CONVERT_DATA_ERROR = 'Uncorrect data.';
const NETCAT_MODULE_COMMENTS_ADMIN_CONVERT_CLASS_ERROR = 'Component error.';
const NETCAT_MODULE_COMMENTS_ADMIN_CONVERT_NO_CATALOGUE_ERROR = 'No sites found.';
const NETCAT_MODULE_COMMENTS_ADMIN_CONVERT_NO_SUBDIVISION = 'No subdivisions found.';
const NETCAT_MODULE_COMMENTS_ADMIN_CONVERT_NO_SUBCLASS = 'No components found.';
const NETCAT_MODULE_COMMENTS_ADMIN_CONVERT_NO_DATA = 'No such objects data.';

//settings
const NETCAT_MODULE_COMMENTS_ADMIN_SETTINGS_MAIN_SETTINGS = 'General Settings';
const NETCAT_MODULE_COMMENTS_ADMIN_SETTINGS_USER_NAME = 'System table "User" field for user name';
const NETCAT_MODULE_COMMENTS_ADMIN_SETTINGS_USER_AVATAR = 'System table "User" field for user avatar';
const NETCAT_MODULE_COMMENTS_ADMIN_SETTINGS_GUEST_USER_NAME = 'Allow an unauthorized user to input a name';
const NETCAT_MODULE_COMMENTS_ADMIN_SETTINGS_GUEST_USER_EMAIL = 'Allow an unauthorized user to input a email';
const NETCAT_MODULE_COMMENTS_ADMIN_SETTINGS_GUEST_USER_NEED = 'Necessarily';
const NETCAT_MODULE_COMMENTS_ADMIN_SETTINGS_QTY = 'Number of comments per page';
const NETCAT_MODULE_COMMENTS_ADMIN_SETTINGS_SHOW_ALL = 'Display the button "Show All"';
const NETCAT_MODULE_COMMENTS_ADMIN_SETTINGS_ORDER_DESC = 'Inverse sorting comments (newest first)';
const NETCAT_MODULE_COMMENTS_ADMIN_SETTINGS_BBCODE = 'Use BB-codes';
const NETCAT_MODULE_COMMENTS_ADMIN_SETTINGS_USE_CAPTCHA = 'Use captcha';
const NETCAT_MODULE_COMMENTS_ADMIN_SETTINGS_RATING = 'Enable rating';
const NETCAT_MODULE_COMMENTS_ADMIN_SETTINGS_PREMODERATION = 'Premoderation';
const NETCAT_MODULE_COMMENTS_ADMIN_SETTINGS_ALLOW_PREMODERATION = 'Allow comments premoderation';
const NETCAT_MODULE_COMMENTS_ADMIN_SETTINGS_PREMODERATION_NO = 'No';
const NETCAT_MODULE_COMMENTS_ADMIN_SETTINGS_PREMODERATION_GUEST = 'Only for unauthorized users';
const NETCAT_MODULE_COMMENTS_ADMIN_SETTINGS_PREMODERATION_ALWAYS = 'Always';
const NETCAT_MODULE_COMMENTS_ADMIN_SETTINGS_SHOW_ADD_BLOCK = 'Immediately show add block';
const NETCAT_MODULE_COMMENTS_ADMIN_SETTINGS_ADD_BLOCK_FIRST = 'Show add block before comments';
const NETCAT_MODULE_COMMENTS_ADMIN_SETTINGS_SAVE_OK = 'Comments settings saved.';
const NETCAT_MODULE_COMMENTS_ADMIN_SETTINGS_AUTH_BUTTONS = 'Show auth buttons';

//template
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_SETTINGS_TEMPLATE = 'Comments view template';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_SETTINGS_TEMPLATE_NEW = 'new template';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_SETTINGS = 'Template settings';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_SETTINGS_USE_DEFAULT = 'use as default';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_SETTINGS_NAME = 'Template name';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_SETTINGS_PREFIX = 'Comments "wall" prefix';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_SETTINGS_COMMENT_BLOCK = 'Comment view block';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_SETTINGS_REPLY_BLOCK = 'Reply view block';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_SETTINGS_LINK_COMMENT = 'Comment link';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_SETTINGS_LINK_REPLY = 'Reply link';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_SETTINGS_LINK_EDIT = 'Edit link';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_SETTINGS_LINK_DROP = 'Delete link';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_SETTINGS_APPEND_BLOCK = 'Comment or reply append block';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_SETTINGS_EDIT_BLOCK = 'Comment or reply edit block';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_SETTINGS_DROP_BLOCK = 'Comment or reply delete block';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_SETTINGS_SUFFIX = 'Comments "wall" suffix';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_SETTINGS_PAGINATION = 'Pagination template';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_SETTINGS_SHOW_ALL = 'Button "Show All"';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_SETTINGS_WARNTEXT = 'Warning text';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_SETTINGS_WARNTEXT_NAME = 'Enter the name';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_SETTINGS_WARNTEXT_EMAIL = 'Enter or enter the correct email';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_SETTINGS_WARNTEXT_NAME_EMAIL = 'Enter the name and the email';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_SETTINGS_WARNTEXT_PARENT = "Comment to which you've written reply has been removed or disabled";
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_SETTINGS_WARNTEXT_CAPTCHA = 'Enter symbols shown on the picture';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_SETTINGS_PREMODERATION = 'Comments premoderation message';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_SETTINGS_NEW_COMMENT_BUTTON = 'Button "Next new comment"';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_SETTINGS_SAVE_OK = 'Template settings saved.';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_SETTINGS_RATING_BLOCK = 'Ratio block';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_SETTINGS_MODERATOR_BLOCK = 'Moderate block';
const NETCAT_MODULE_COMMENTS_ADMIN_TEMPLATE_SETTINGS_NOT_USER_AUTH_BLOCK = 'Block output for unauthorized users';

//subscribe
const NETCAT_MODULE_COMMENTS_ADMIN_SUBSCRIBE_ADD = 'Add subscription';
const NETCAT_MODULE_COMMENTS_ADMIN_SUBSCRIBE_ADD_EXPLAIN = 'You must choose essence(site, subdivision, subclass or message) and user.';
const NETCAT_MODULE_COMMENTS_ADMIN_SUBSCRIBE_ADD_NOUSER = 'User not choosen';
const NETCAT_MODULE_COMMENTS_ADMIN_SUBSCRIBE_ADD_NOESSENCE = 'Essence not choosen';
const NETCAT_MODULE_COMMENTS_ADMIN_SUBSCRIBE_ADD_SUBSCRIBED = 'User already subscribed on this essence';
const NETCAT_MODULE_COMMENTS_ADMIN_SUBSCRIBE_ADD_OK = 'User %s succesfully subscribed';
const NETCAT_MODULE_COMMENTS_ADMIN_SUBSCRIBE_DELETE_CONFIRM = 'This subscribes will be deleted';
const NETCAT_MODULE_COMMENTS_ADMIN_SUBSCRIBE_DELETE_NOTSELECT = 'No subscribes for deletion';
const NETCAT_MODULE_COMMENTS_ADMIN_SUBSCRIBE_DELETE_OK = 'Subscribes deleted: %s';
const NETCAT_MODULE_COMMENTS_ADMIN_SUBSCRIBE_SETTINGS_ALLOW = 'subscriber allow';
const NETCAT_MODULE_COMMENTS_ADMIN_SUBSCRIBE_SETTINGS_AUTO = 'Autosubscribe user who adds comment';
const NETCAT_MODULE_COMMENTS_ADMIN_SUBSCRIBE_SETTINGS_BLOCK = 'Subscribe link';
const NETCAT_MODULE_COMMENTS_ADMIN_SUBSCRIBE_SETTINGS_MAIL_TEMPLATE = 'Mail body';
const NETCAT_MODULE_COMMENTS_ADMIN_SUBSCRIBE_SETTINGS_MAIL_SUBJECT = 'Mail subject';
const NETCAT_MODULE_COMMENTS_ADMIN_SUBSCRIBE_SETTINGS_SAVE_OK = 'Subscriptions and notifications settings saved.';
const NETCAT_MODULE_COMMENTS_ADMIN_SUBSCRIBE_SETTINGS_ADMIN = 'Admin notification';
const NETCAT_MODULE_COMMENTS_ADMIN_SUBSCRIBE_SETTINGS_ADMIN_ALLOW = 'Notify administrator of new comments';
const NETCAT_MODULE_COMMENTS_ADMIN_SUBSCRIBE_SETTINGS_ADMIN_EMAIL = 'Notification email';

const NETCAT_MODULE_COMMENTS_ADMIN_SUBSCRIBE_LIST_MESSAGE = 'Object %s in subclass %s';
const NETCAT_MODULE_COMMENTS_ADMIN_SUBSCRIBE_LIST_CC = 'Subclass %s';
const NETCAT_MODULE_COMMENTS_ADMIN_SUBSCRIBE_LIST_SUB = 'Subdivision %s';
const NETCAT_MODULE_COMMENTS_ADMIN_SUBSCRIBE_LIST_CAT = 'Site %s';

//optimize
const NETCAT_MODULE_COMMENTS_ADMIN_OPTIMIZE = 'Optimize data';
const NETCAT_MODULE_COMMENTS_ADMIN_OPTIMIZE_DO = 'Recalculate comments and replies';
const NETCAT_MODULE_COMMENTS_ADMIN_OPTIMIZE_DO_BUTTON = 'Optimize';
const NETCAT_MODULE_COMMENTS_ADMIN_OPTIMIZE_OK = 'Recalculated rows: %COUNT';
const NETCAT_MODULE_COMMENTS_ADMIN_OPTIMIZE_NO_DATA = 'No data to recalculate';

const NETCAT_MODULE_COMMENTS_CLASS_UNRECOGNIZED_OBJECT_CALLING = 'Unrecognized object calling';
const NETCAT_MODULE_COMMENTS_CLASS_UNCORRECT_DATA_FORMAT = 'Uncorrect data format';

const NETCAT_MODULE_COMMENTS_SPAM_FROM_EMAIL_NOTICE = "Sender's email field is empty. For notifications to work correctly, you must fill Sender's email field in General settings";

const NETCAT_MODULE_COMMENTS_ADD_COMMENT_USER_AUTH = 'To add comments, you need to log in';
