<?php

const NETCAT_MODULE_BILLS = 'Bills and acts';
const NETCAT_MODULE_BILLS_TITLE = 'Bills and acts';
const NETCAT_MODULE_BILLS_DESCRIPTION = 'Bills and acts.';

const NETCAT_MODULE_BILLS_INFORMATION = 'Information';
const NETCAT_MODULE_BILLS_MANAGER = 'Bills and acts';
const NETCAT_MODULE_BILLS_BILLS = 'Bills';
const NETCAT_MODULE_BILLS_ACTS = 'Acts';
const NETCAT_MODULE_BILLS_SETTINGS = 'Settings';
const NETCAT_MODULE_BILLS_CATALOGS = 'Catalogs';
const NETCAT_MODULE_BILLS_STATUSES = 'Bill statuses';
const NETCAT_MODULE_BILLS_SERVICES = 'Services';
const NETCAT_MODULE_BILLS_CUSTOMERS = 'Customers';

# Bills
const NETCAT_MODULE_BILLS_BILL_ADD = 'Add bill';
const NETCAT_MODULE_BILLS_BILL_EDIT = 'Edit bill';

const NETCAT_MODULE_BILLS_BILL_NUMBER = 'Bill №';
const NETCAT_MODULE_BILLS_BILL_FROM = 'from';

const NETCAT_MODULE_BILLS_BILL_CLIENT_NAME = 'Client name';
const NETCAT_MODULE_BILLS_BILL_CLIENT_ADDRESS = 'Client address';

const NETCAT_MODULE_BILLS_BILL_ADD_POSITION = 'Add position';
const NETCAT_MODULE_BILLS_BILL_IS_PAID = 'The bill is paid';
const NETCAT_MODULE_BILLS_BILL_IS_PAID_SHORT = 'Is paid';

const NETCAT_MODULE_BILLS_BILL_JURIDICAL = 'on jur. face';
const NETCAT_MODULE_BILLS_BILL_PHIYSICAL = 'on phis. face';

const NETCAT_MODULE_BILLS_BILL_LINK_PDF = 'Link to PDF bill';
const NETCAT_MODULE_BILLS_BILL_LINK_PDF_WITH_SIGN = 'Link to PDF bill with the sign';

const NETCAT_MODULE_BILLS_BILL_EMPTY = 'No bills';

const NETCAT_MODULE_BILLS_BILL_SEARCH = 'Search in customers';
const NETCAT_MODULE_BILLS_BILL_SEARCH_EMPTY = 'The bill not found';

const NETCAT_MODULE_BILLS_BILL_CONFIRM_DELETE = 'Really delete this position?';

# Acts
const NETCAT_MODULE_BILLS_ACT_ADD = 'Add act';
const NETCAT_MODULE_BILLS_ACT_EDIT = 'Edit act';
const NETCAT_MODULE_BILLS_ACT_NUMBER = 'Act №';
const NETCAT_MODULE_BILLS_ACT_BY_BILL = 'By bill';
const NETCAT_MODULE_BILLS_ACT_EMPTY = 'No acts';
const NETCAT_MODULE_BILLS_ACT_SEARCH = 'Search in customers';

const NETCAT_MODULE_BILLS_ACT_NOT_FOUND = 'Act not found';

const NETCAT_MODULE_BILLS_ACT_LINK_TO_PDF = 'Link to PDF';
const NETCAT_MODULE_BILLS_ACT_LINK_TO_PDF_WITH_SIGN = 'Link to PDF with the sign';

# Clients
const NETCAT_MODULE_BILLS_CLIENT_ADD = 'New client';
const NETCAT_MODULE_BILLS_CLIENT_EDIT = 'Edit client';
const NETCAT_MODULE_BILLS_CLIENT_OPF = 'OPF';
const NETCAT_MODULE_BILLS_CLIENT_NAME = 'Name';
const NETCAT_MODULE_BILLS_CLIENT_LEGAL_ADDRESS = 'Legal address';
const NETCAT_MODULE_BILLS_CLIENT_PHONE = 'Phone';
const NETCAT_MODULE_BILLS_CLIENT_INN = 'INN';
const NETCAT_MODULE_BILLS_CLIENT_KPP = 'KPP';
const NETCAT_MODULE_BILLS_CLIENT_PAYMENT_DETAILS = 'Paiment details';
const NETCAT_MODULE_BILLS_CLIENT_BANK_NAME = 'Name of the bank';
const NETCAT_MODULE_BILLS_CLIENT_BANK_CURRENT_ACCOUNT = 'Current account';
const NETCAT_MODULE_BILLS_CLIENT_BANK_CORRESPONDENT_ACCOUNT = 'Correspondent account';
const NETCAT_MODULE_BILLS_CLIENT_BANK_INN = 'INN';
const NETCAT_MODULE_BILLS_CLIENT_BANK_BIK = 'BIK';

const NETCAT_MODULE_BILLS_CLIENT_NOT_FOUND = 'Client not found';

const NETCAT_MODULE_BILLS_CLIENT_CHANGES_OK = 'Changes saved successfully';
const NETCAT_MODULE_BILLS_CLIENT_EMPTY = 'No clients';

# Information
const NETCAT_MODULE_BILLS_INFORMATION_STAT_ALL = 'All';
const NETCAT_MODULE_BILLS_INFORMATION_STAT_PAID = 'Paid';
const NETCAT_MODULE_BILLS_INFORMATION_STAT_UNPAID = 'Unpaid';

# Settings
const NETCAT_MODULE_BILLS_SETTINGS_VAT = 'Vat';
const NETCAT_MODULE_BILLS_SETTINGS_SECRET_KEY = 'Secret key';
const NETCAT_MODULE_BILLS_SETTINGS_COMPANY_DETAILS = 'Company details';
const NETCAT_MODULE_BILLS_SETTINGS_OPF = 'OPF';
const NETCAT_MODULE_BILLS_SETTINGS_NAME = 'Name';
const NETCAT_MODULE_BILLS_SETTINGS_LEGAL_ADDRESS = 'Legal address';
const NETCAT_MODULE_BILLS_SETTINGS_PHONE = 'Phone';
const NETCAT_MODULE_BILLS_SETTINGS_INN = 'INN';
const NETCAT_MODULE_BILLS_SETTINGS_KPP = 'KPP';
const NETCAT_MODULE_BILLS_SETTINGS_PAYMENT_DETAILS = 'Paiment details';
const NETCAT_MODULE_BILLS_SETTINGS_BANK_NAME = 'Name of the bank';
const NETCAT_MODULE_BILLS_SETTINGS_BANK_CURRENT_ACCOUNT = 'Current account';
const NETCAT_MODULE_BILLS_SETTINGS_BANK_CORRESPONDENT_ACCOUNT = 'Correspondent account';
const NETCAT_MODULE_BILLS_SETTINGS_BANK_INN = 'INN';
const NETCAT_MODULE_BILLS_SETTINGS_BANK_BIK = 'BIK';

const NETCAT_MODULE_BILLS_SETTINGS_GRAPHIC_ELEMENTS = 'Graphic elements';
const NETCAT_MODULE_BILLS_SETTINGS_LOGO = 'Logo';
const NETCAT_MODULE_BILLS_SETTINGS_DIRECTOR_SIGN = 'The signature of director';
const NETCAT_MODULE_BILLS_SETTINGS_BUCH_SIGN = 'The signature of accountant';
const NETCAT_MODULE_BILLS_SETTINGS_PRINT = 'Print';

const NETCAT_MODULE_BILLS_SETTINGS_SAVED = 'The settings are saved';

# Common
const NETCAT_MODULE_BILLS_CLIENT = 'Client';
const NETCAT_MODULE_BILLS_NAME = 'Name';
const NETCAT_MODULE_BILLS_UNIT = 'Unit';
const NETCAT_MODULE_BILLS_COUNT = 'Count';
const NETCAT_MODULE_BILLS_PRICE = 'Price';
const NETCAT_MODULE_BILLS_SUM = 'Sum';
const NETCAT_MODULE_BILLS_DATE = 'Date';
const NETCAT_MODULE_BILLS_SELECT = 'Select';
const NETCAT_MODULE_BILLS_SAVE = 'Save';
const NETCAT_MODULE_BILLS_ADD = 'Add';
const NETCAT_MODULE_BILLS_ADD_JURIDICAL = 'Add juridical bill';
const NETCAT_MODULE_BILLS_ADD_PHYSICAL = 'Add physical bill';
const NETCAT_MODULE_BILLS_BACK = 'Back';
const NETCAT_MODULE_BILLS_DELETE = 'Delete';
const NETCAT_MODULE_BILLS_SHOW = 'Show';

const NETCAT_MODULE_BILLS_PDF = 'PDF';
const NETCAT_MODULE_BILLS_PDF_WITH_SIGN = 'PDF with the sign';
const NETCAT_MODULE_BILLS_PDF_WITH_SIGN_AND_PRINT = 'PDF with the sign and print';
const NETCAT_MODULE_BILLS_BATCH_LOADING = 'Batch loading';

const NETCAT_MODULE_BILLS_CONFIRM_DELETE = 'Confirm delete';

const NETCAT_MODULE_BILLS_YES = 'Yes';
const NETCAT_MODULE_BILLS_NO = 'No';

const NETCAT_MODULE_BILLS_VALIDATE_NO_ACT_NUMBER = 'No act number';
const NETCAT_MODULE_BILLS_VALIDATE_NO_BILL_NUMBER = 'No bill number';
const NETCAT_MODULE_BILLS_VALIDATE_NO_DATE = 'No date';
const NETCAT_MODULE_BILLS_VALIDATE_NO_ACCOUNT = 'No account';
const NETCAT_MODULE_BILLS_VALIDATE_NO_CLIENT = 'No client';
const NETCAT_MODULE_BILLS_VALIDATE_NO_POSITION = 'No position';