<?php

const NC_OPENSTAT_COUNTER = '<!--OPENSTAT_COUNTER-->';
const NETCAT_MODULE_STATS_DESCRIPTION = 'Отчеты о статистике посещений на сайте.';

const NETCAT_MODULE_STATS_TYPE_MAIN = 'Сводная статистика';
const NETCAT_MODULE_STATS_TYPE_GUESTS = 'Посещаемость';
const NETCAT_MODULE_STATS_TYPE_PAGES = 'Популярность страниц';
const NETCAT_MODULE_STATS_TYPE_EXTPAGES = 'Ссылающиеся страницы';
const NETCAT_MODULE_STATS_TYPE_USERAGENTS = 'Браузеры';
const NETCAT_MODULE_STATS_TYPE_OS = 'Операционные системы';
const NETCAT_MODULE_STATS_TYPE_IP = 'IP-адреса';
const NETCAT_MODULE_STATS_TYPE_GEO = 'География';
const NETCAT_MODULE_STATS_TYPE_PHRASES = 'Поисковые фразы';

const NETCAT_MODULE_STATS_TXT_PERIOD = 'за период с';
const NETCAT_MODULE_STATS_TXT_OVER = 'по';
const NETCAT_MODULE_STATS_BUT_SHOW = 'Показать';

const NETCAT_MODULE_STATS_PERIOD_TODAY = 'сегодня';
const NETCAT_MODULE_STATS_PERIOD_YESTERDAY = 'вчера';
const NETCAT_MODULE_STATS_PERIOD_WEEK = 'неделя';
const NETCAT_MODULE_STATS_PERIOD_PER_WEEK = 'в неделю';
const NETCAT_MODULE_STATS_PERIOD_MONTHS = 'месяц';
const NETCAT_MODULE_STATS_PERIOD_TOTAL = 'всего';
const NETCAT_MODULE_STATS_PERIOD_ALL = 'весь период';

const NETCAT_MODULE_STATS_HOUR = 'Час';
const NETCAT_MODULE_STATS_HOSTS = 'Хосты';
const NETCAT_MODULE_STATS_HITS = 'Хиты';
const NETCAT_MODULE_STATS_USERS = 'Посетители';
const NETCAT_MODULE_STATS_COUNTRY = 'Страна';

const NETCAT_MODULE_STATS_BROWSER = 'Браузер';
const NETCAT_MODULE_STATS_PERCENTINGROUP = 'Процент в группе';
const NETCAT_MODULE_STATS_TXT_TIPONE = 'В скобках указано, сколько новых хостов/посетителей пришло на сайт в течение часа.';
const NETCAT_MODULE_STATS_PAGE = 'Страница';
const NETCAT_MODULE_STATS_TXT_TIPTWO = 'Среднее число хостов, хитов и посетителей за указанный период';
const NETCAT_MODULE_STATS_OS = 'Операционная система';
const NETCAT_MODULE_STATS_IP = 'IP-адрес';
const NETCAT_MODULE_STATS_PHRASE = 'Фраза';

const NETCAT_MODULE_STATS_NOT_DEFINED = 'не определено';
const NETCAT_MODULE_STATS_CLEAN = 'Очистить статистику до даты:';
const NETCAT_MODULE_STATS_CLEAN_BUTTON = 'Очистить';
const NETCAT_MODULE_STATS_CLEAN_SUCCESS = 'Статистика успешно очищена.';
const NETCAT_MODULE_STATS_SHOW_BUTTON = 'Показать статистику по выбранному сайту';

const NETCAT_MODULE_STATS_TXT_HOSTSPERPERIOD = 'Количество хостов, хитов и посетителей за указанный период';

const NETCAT_MODULE_STATS_UNKNOWN = 'Неизвестно';
const NETCAT_MODULE_STATS_PIE_OTHER = 'Прочие';



const NETCAT_MODULE_STATS_AD = 'АНДОРРА';
const NETCAT_MODULE_STATS_AE = 'Объединенные Арабские Эмираты';
const NETCAT_MODULE_STATS_AF = 'АФГАНИСТАН';
const NETCAT_MODULE_STATS_AG = 'Антигуа и Барбуда';
const NETCAT_MODULE_STATS_AL = 'АЛБАНИЯ';
const NETCAT_MODULE_STATS_AM = 'АРМЕНИЯ';
const NETCAT_MODULE_STATS_AN = 'NETHERLANDS ANTILLES';
const NETCAT_MODULE_STATS_AO = 'АНГОЛА';
const NETCAT_MODULE_STATS_AQ = 'АНТАРКТИКЕ';
const NETCAT_MODULE_STATS_AR = 'АРГЕНТИНА';
const NETCAT_MODULE_STATS_AS = 'АМЕРИКАНСКОЕ САМОА';
const NETCAT_MODULE_STATS_AT = 'АВСТРИЯ';
const NETCAT_MODULE_STATS_AU = 'АВСТРАЛИЯ';
const NETCAT_MODULE_STATS_AW = 'АРУБА';
const NETCAT_MODULE_STATS_AZ = 'АЗЕРБАЙДЖАН';
const NETCAT_MODULE_STATS_BA = 'Босния и Герцеговина';
const NETCAT_MODULE_STATS_BB = 'БАРБАДОС';
const NETCAT_MODULE_STATS_BD = 'БАНГЛАДЕШ';
const NETCAT_MODULE_STATS_BE = 'БЕЛЬГИЯ';
const NETCAT_MODULE_STATS_BG = 'БОЛГАРИЯ';
const NETCAT_MODULE_STATS_BH = 'БАХРЕЙН';
const NETCAT_MODULE_STATS_BI = 'БУРУНДИ';
const NETCAT_MODULE_STATS_BJ = 'БЕНИН';
const NETCAT_MODULE_STATS_BM = 'Бермудские острова';
const NETCAT_MODULE_STATS_BN = 'BRUNEI DARUSSALAM';
const NETCAT_MODULE_STATS_BO = 'БОЛИВИЯ';
const NETCAT_MODULE_STATS_BR = 'БРАЗИЛИЯ';
const NETCAT_MODULE_STATS_BS = 'BAHAMAS';
const NETCAT_MODULE_STATS_BT = 'BHUTAN';
const NETCAT_MODULE_STATS_BW = 'БОТСВАНА';
const NETCAT_MODULE_STATS_BY = 'БЕЛАРУСЬ';
const NETCAT_MODULE_STATS_BZ = 'БЕЛИЗ';
const NETCAT_MODULE_STATS_CA = 'КАНАДА';
const NETCAT_MODULE_STATS_CD = 'ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА КОНГО';
const NETCAT_MODULE_STATS_CF = 'Центральноафриканской Республике';
const NETCAT_MODULE_STATS_CG = 'КОНГО';
const NETCAT_MODULE_STATS_CH = 'ШВЕЙЦАРИЯ';
const NETCAT_MODULE_STATS_CI = 'КОТ DIVOIRE';
const NETCAT_MODULE_STATS_CK = 'COOK ISLANDS';
const NETCAT_MODULE_STATS_CL = 'ЧИЛИ';
const NETCAT_MODULE_STATS_CM = 'КАМЕРУН';
const NETCAT_MODULE_STATS_CN = 'КИТАЙ';
const NETCAT_MODULE_STATS_CO = 'КОЛУМБИЯ';
const NETCAT_MODULE_STATS_CR = 'КОСТА-РИКА';
const NETCAT_MODULE_STATS_CS = 'Сербия и Черногория';
const NETCAT_MODULE_STATS_CU = 'КУБА';
const NETCAT_MODULE_STATS_CV = 'CAPE VERDE';
const NETCAT_MODULE_STATS_CY = 'КИПР';
const NETCAT_MODULE_STATS_CZ = 'ЧЕШСКАЯ РЕСПУБЛИКА';
const NETCAT_MODULE_STATS_DE = 'ГЕРМАНИЯ';
const NETCAT_MODULE_STATS_DJ = 'DJIBOUTI';
const NETCAT_MODULE_STATS_DK = 'ДАНИЯ';
const NETCAT_MODULE_STATS_DM = 'ДОМИНИКА';
const NETCAT_MODULE_STATS_DO = 'ДОМИНИКАНСКАЯ РЕСПУБЛИКА';
const NETCAT_MODULE_STATS_DZ = 'АЛЖИР';
const NETCAT_MODULE_STATS_EC = 'ЭКВАДОР';
const NETCAT_MODULE_STATS_EE = 'ЭСТОНИЯ';
const NETCAT_MODULE_STATS_EG = 'ЕГИПЕТ';
const NETCAT_MODULE_STATS_ER = 'ЭРИТРЕЯ';
const NETCAT_MODULE_STATS_ES = 'ИСПАНИЯ';
const NETCAT_MODULE_STATS_ET = 'ЭФИОПИЯ';
const NETCAT_MODULE_STATS_FI = 'ФИНЛЯНДИЯ';
const NETCAT_MODULE_STATS_FJ = 'ФИДЖИ';
const NETCAT_MODULE_STATS_FK = 'Фолклендских (Мальвинских)';
const NETCAT_MODULE_STATS_FM = 'Федеративные Штаты Микронезии';
const NETCAT_MODULE_STATS_FO = 'FAROE ISLANDS';
const NETCAT_MODULE_STATS_FR = 'ФРАНЦИЯ';
const NETCAT_MODULE_STATS_GA = 'GABON';
const NETCAT_MODULE_STATS_GB = 'ВЕЛИКОБРИТАНИЯ';
const NETCAT_MODULE_STATS_GD = 'GRENADA';
const NETCAT_MODULE_STATS_GE = 'ГРУЗИЯ';
const NETCAT_MODULE_STATS_GF = 'FRENCH GUIANA';
const NETCAT_MODULE_STATS_GH = 'ГАНА';
const NETCAT_MODULE_STATS_GI = 'ГИБРАЛТАР';
const NETCAT_MODULE_STATS_GL = 'ГРЕНЛАНДИЯ';
const NETCAT_MODULE_STATS_GM = 'ГАМБИЯ';
const NETCAT_MODULE_STATS_GN = 'ГВИНЕЯ';
const NETCAT_MODULE_STATS_GP = 'GUADELOUPE';
const NETCAT_MODULE_STATS_GQ = 'EQUATORIAL GUINEA';
const NETCAT_MODULE_STATS_GR = 'ГРЕЦИЯ';
const NETCAT_MODULE_STATS_GT = 'ГВАТЕМАЛА';
const NETCAT_MODULE_STATS_GU = 'ГУАМ';
const NETCAT_MODULE_STATS_GW = 'GUINEA-BISSAU';
const NETCAT_MODULE_STATS_GY = 'ГАЙАНА';
const NETCAT_MODULE_STATS_HK = 'HONG KONG';
const NETCAT_MODULE_STATS_HN = 'HONDURAS';
const NETCAT_MODULE_STATS_HR = 'ХОРВАТИЯ';
const NETCAT_MODULE_STATS_HT = 'ГАИТИ';
const NETCAT_MODULE_STATS_HU = 'ВЕНГРИЯ';
const NETCAT_MODULE_STATS_ID = 'ИНДОНЕЗИЯ';
const NETCAT_MODULE_STATS_IE = 'ИРЛАНДИЯ';
const NETCAT_MODULE_STATS_IL = 'ИЗРАИЛЬ';
const NETCAT_MODULE_STATS_IN = 'ИНДИЯ';
const NETCAT_MODULE_STATS_IO = 'Британская территория в Индийском океане';
const NETCAT_MODULE_STATS_IQ = 'ИРАК';
const NETCAT_MODULE_STATS_IR = 'ИСЛАМСКОЙ РЕСПУБЛИКИ ИРАН';
const NETCAT_MODULE_STATS_IS = 'ИСЛАНДИЯ';
const NETCAT_MODULE_STATS_IT = 'ИТАЛИЯ';
const NETCAT_MODULE_STATS_JM = 'JAMAICA';
const NETCAT_MODULE_STATS_JO = 'JORDAN';
const NETCAT_MODULE_STATS_JP = 'ЯПОНИЯ';
const NETCAT_MODULE_STATS_KE = 'КЕНИЯ';
const NETCAT_MODULE_STATS_KG = 'КЫРГЫЗСТАН';
const NETCAT_MODULE_STATS_KH = 'КАМБОДЖА';
const NETCAT_MODULE_STATS_KI = 'KIRIBATI';
const NETCAT_MODULE_STATS_KM = 'COMOROS';
const NETCAT_MODULE_STATS_KN = 'Сент-Китс и Невис';
const NETCAT_MODULE_STATS_KR = 'Республика Корея';
const NETCAT_MODULE_STATS_KW = 'КУВЕЙТ';
const NETCAT_MODULE_STATS_KY = 'КАЙМАНОВЫ ОСТРОВА';
const NETCAT_MODULE_STATS_KZ = 'КАЗАХСТАН';
const NETCAT_MODULE_STATS_LA = 'Лаосская Народно-Демократическая республика';
const NETCAT_MODULE_STATS_LB = 'ЛИВАН';
const NETCAT_MODULE_STATS_LC = 'SAINT LUCIA';
const NETCAT_MODULE_STATS_LI = 'ЛИХТЕНШТЕЙН';
const NETCAT_MODULE_STATS_LK = 'SRI LANKA';
const NETCAT_MODULE_STATS_LR = 'ЛИБЕРИЯ';
const NETCAT_MODULE_STATS_LS = 'LESOTHO';
const NETCAT_MODULE_STATS_LT = 'ЛИТВА';
const NETCAT_MODULE_STATS_LU = 'ЛЮКСЕМБУРГ';
const NETCAT_MODULE_STATS_LV = 'ЛАТВИЯ';
const NETCAT_MODULE_STATS_LY = 'Ливийская Арабская Джамахирия';
const NETCAT_MODULE_STATS_MA = 'МАРОККО';
const NETCAT_MODULE_STATS_MC = 'МОНАКО';
const NETCAT_MODULE_STATS_MD = 'Республика Молдова';
const NETCAT_MODULE_STATS_MG = 'МАДАГАСКАР';
const NETCAT_MODULE_STATS_MH = 'MARSHALL ISLANDS';
const NETCAT_MODULE_STATS_MK = 'Бывшей югославской Республики Македонии';
const NETCAT_MODULE_STATS_ML = 'МАЛИ';
const NETCAT_MODULE_STATS_MM = 'MYANMAR';
const NETCAT_MODULE_STATS_MN = 'МОНГОЛИЯ';
const NETCAT_MODULE_STATS_MO = 'МАКАО';
const NETCAT_MODULE_STATS_MP = 'Северные Марианские острова';
const NETCAT_MODULE_STATS_MQ = 'MARTINIQUE';
const NETCAT_MODULE_STATS_MR = 'МАВРИТАНИЯ';
const NETCAT_MODULE_STATS_MT = 'МАЛЬТА';
const NETCAT_MODULE_STATS_MU = 'МАВРИКИЙ';
const NETCAT_MODULE_STATS_MV = 'MALDIVES';
const NETCAT_MODULE_STATS_MW = 'MALAWI';
const NETCAT_MODULE_STATS_MX = 'МЕКСИКА';
const NETCAT_MODULE_STATS_MY = 'МАЛАЙЗИЯ';
const NETCAT_MODULE_STATS_MZ = 'МОЗАМБИК';
const NETCAT_MODULE_STATS_NA = 'НАМИБИЯ';
const NETCAT_MODULE_STATS_NC = 'НОВАЯ КАЛЕДОНИЯ';
const NETCAT_MODULE_STATS_NE = 'НИГЕРИЯ';
const NETCAT_MODULE_STATS_NF = 'NORFOLK ISLAND';
const NETCAT_MODULE_STATS_NG = 'НИГЕРИЯ';
const NETCAT_MODULE_STATS_NI = 'НИКАРАГУА';
const NETCAT_MODULE_STATS_NL = 'НИДЕРЛАНДЫ';
const NETCAT_MODULE_STATS_NO = 'НОРВЕГИЯ';
const NETCAT_MODULE_STATS_NP = 'НЕПАЛ';
const NETCAT_MODULE_STATS_NR = 'NAURU';
const NETCAT_MODULE_STATS_NZ = 'НОВАЯ ЗЕЛАНДИЯ';
const NETCAT_MODULE_STATS_OM = 'ОМАН';
const NETCAT_MODULE_STATS_PA = 'ПАНАМА';
const NETCAT_MODULE_STATS_PE = 'ПЕРУ';
const NETCAT_MODULE_STATS_PF = 'FRENCH POLYNESIA';
const NETCAT_MODULE_STATS_PG = 'ПАПУА-НОВАЯ ГВИНЕЯ';
const NETCAT_MODULE_STATS_PH = 'ФИЛИППИНЫ';
const NETCAT_MODULE_STATS_PK = 'ПАКИСТАН';
const NETCAT_MODULE_STATS_PL = 'ПОЛЬША';
const NETCAT_MODULE_STATS_PR = 'ПУЭРТО-РИКО';
const NETCAT_MODULE_STATS_PS = 'Палестинской территории,  оккупированной';
const NETCAT_MODULE_STATS_PT = 'ПОРТУГАЛИЯ';
const NETCAT_MODULE_STATS_PW = 'ПАЛАУ';
const NETCAT_MODULE_STATS_PY = 'ПАРАГВАЙ';
const NETCAT_MODULE_STATS_QA = 'КАТАР';
const NETCAT_MODULE_STATS_RE = 'REUNION';
const NETCAT_MODULE_STATS_RO = 'РУМЫНИЯ';
const NETCAT_MODULE_STATS_RU = 'РОССИЙСКАЯ ФЕДЕРАЦИЯ';
const NETCAT_MODULE_STATS_RW = 'РУАНДА';
const NETCAT_MODULE_STATS_SA = 'САУДОВСКАЯ АРАВИЯ';
const NETCAT_MODULE_STATS_SB = 'СОЛОМОНОВЫ ОСТРОВА';
const NETCAT_MODULE_STATS_SC = 'Сейшельские острова';
const NETCAT_MODULE_STATS_SD = 'СУДАН';
const NETCAT_MODULE_STATS_SE = 'ШВЕЦИЯ';
const NETCAT_MODULE_STATS_SG = 'СИНГАПУР';
const NETCAT_MODULE_STATS_SI = 'СЛОВЕНИЯ';
const NETCAT_MODULE_STATS_SK = 'СЛОВАКИЯ';
const NETCAT_MODULE_STATS_SL = 'СЬЕРРА-ЛЕОНЕ';
const NETCAT_MODULE_STATS_SM = 'САН-МАРИНО';
const NETCAT_MODULE_STATS_SN = 'SENEGAL';
const NETCAT_MODULE_STATS_SO = 'СОМАЛИ';
const NETCAT_MODULE_STATS_SR = 'SURINAME';
const NETCAT_MODULE_STATS_ST = 'Сан-Томе и Принсипи';
const NETCAT_MODULE_STATS_SV = 'САЛЬВАДОР';
const NETCAT_MODULE_STATS_SY = 'Сирийская Арабская Республика';
const NETCAT_MODULE_STATS_SZ = 'SWAZILAND';
const NETCAT_MODULE_STATS_TD = 'ЧАД';
const NETCAT_MODULE_STATS_TF = 'Французские Южные Территории';
const NETCAT_MODULE_STATS_TG = 'ТОГО';
const NETCAT_MODULE_STATS_TH = 'ТАИЛАНД';
const NETCAT_MODULE_STATS_TJ = 'ТАДЖИКИСТАН';
const NETCAT_MODULE_STATS_TK = 'ТОКЕЛАУ';
const NETCAT_MODULE_STATS_TL = 'Тимор-Лешти';
const NETCAT_MODULE_STATS_TM = 'ТУРКМЕНИСТАН';
const NETCAT_MODULE_STATS_TN = 'ТУНИС';
const NETCAT_MODULE_STATS_TO = 'ТОНГА';
const NETCAT_MODULE_STATS_TR = 'ТУРЦИЯ';
const NETCAT_MODULE_STATS_TT = 'Тринидад и Тобаго';
const NETCAT_MODULE_STATS_TV = 'TUVALU';
const NETCAT_MODULE_STATS_TW = 'ТАЙВАНЬ';
const NETCAT_MODULE_STATS_TZ = 'Объединенная Республика Танзания';
const NETCAT_MODULE_STATS_UA = 'УКРАИНА';
const NETCAT_MODULE_STATS_UG = 'УГАНДА';
const NETCAT_MODULE_STATS_US = 'СОЕДИНЕННЫЕ ШТАТЫ';
const NETCAT_MODULE_STATS_UY = 'УРУГВАЙ';
const NETCAT_MODULE_STATS_UZ = 'УЗБЕКИСТАН';
const NETCAT_MODULE_STATS_VA = 'Ватикан';
const NETCAT_MODULE_STATS_VC = 'Сент-Винсент и Гренадины';
const NETCAT_MODULE_STATS_VE = 'ВЕНЕСУЭЛА';
const NETCAT_MODULE_STATS_VG = 'ВИРГИНСКИЕ ОСТРОВА,  БРИТАНСКИЕ';
const NETCAT_MODULE_STATS_VI = 'Виргинские Острова,  США';
const NETCAT_MODULE_STATS_VN = 'ВЬЕТНАМ';
const NETCAT_MODULE_STATS_VU = 'VANUATU';
const NETCAT_MODULE_STATS_WS = 'САМОА';
const NETCAT_MODULE_STATS_YE = 'YEMEN';
const NETCAT_MODULE_STATS_YT = 'МАЙОТТА';
const NETCAT_MODULE_STATS_ZA = 'ЮЖНАЯ АФРИКА';
const NETCAT_MODULE_STATS_ZM = 'ZAMBIA';
const NETCAT_MODULE_STATS_ZW = 'ЗИМБАБВЕ';
const NETCAT_MODULE_STATS_YU = 'ЮГОСЛАВИЯ';
const NETCAT_MODULE_STATS_EU = 'ЕВРОПЕЙСКИЙ СОЮЗ';


const NETCAT_MODULE_STATS_SAVE_CHANGES = 'Сохранить изменения';
const NETCAT_MODULE_STATS_CHANGES_SAVED = 'Изменения сохранены';
const NETCAT_MODULE_STATS_OPENSTAT_API_COUNTER_CREATED = "Счетчик создан, и с этого момента он начнет собирать статистику вашего сайта.<br />\nОтчеты вы можете посмотреть <a href='admin.php?sub_view=reports&phase=%PASE_ID'>здесь</a>.";
const NETCAT_MODULE_STATS_OPENSTAT_USER_COUNTER_CREATED = "Счетчик создан, и с этого момента он начнет собирать статистику вашего сайта.<br />\nОтчеты вы можете посмотреть на сайте <a href='http://www.openstat.ru/' target='_blank'>Openstat</a>.";

const NETCAT_MODULE_STATS_ADMIN_TAB_NC_STAT = 'Статистика Netcat';
const NETCAT_MODULE_STATS_ADMIN_TAB_OPENSTAT = 'Статистика Openstat';
const NETCAT_MODULE_STATS_ADMIN_TAB_OPENSTAT_TOOLBAR_REPORT = 'Отчёты';
const NETCAT_MODULE_STATS_ADMIN_TAB_OPENSTAT_TOOLBAR_COUNTERS = 'Счетчики';
const NETCAT_MODULE_STATS_ADMIN_TAB_OPENSTAT_TOOLBAR_TEMPLATES = 'Макеты дизайна';
const NETCAT_MODULE_STATS_ADMIN_TAB_OPENSTAT_TOOLBAR_TOOLS = 'Настройки';

const NETCAT_MODULE_STATS_ADMIN_TAB_ANALYTICS = 'Аналитика и Метрика';
const NETCAT_MODULE_STATS_ADMIN_ANALYTICS_ENABLE = 'Добавлять на страницы сайта код Яндекс.Метрики и Google Analytics и код для интеграции Netcat с ними';
const NETCAT_MODULE_STATS_ADMIN_ANALYTICS_ECOMMERCE_ENABLE = 'Включить регистрацию событий электронной коммерции';
const NETCAT_MODULE_STATS_ADMIN_ANALYTICS_SCRIPT_POSITION = 'Место вставки кода счётчиков';
const NETCAT_MODULE_STATS_ADMIN_ANALYTICS_SCRIPT_POSITION_BODY_TOP = 'вверху <body>';
const NETCAT_MODULE_STATS_ADMIN_ANALYTICS_SCRIPT_POSITION_BODY_BOTTOM = 'внизу <body>';
const NETCAT_MODULE_STATS_ADMIN_ANALYTICS_GA_CODE = 'Код отслеживания Google Universal Analytics или Google Tag Manager';
const NETCAT_MODULE_STATS_ADMIN_ANALYTICS_YM_CODE = 'Код счётчика Яндекс.Метрики';

const NETCAT_MODULE_STATS_ENABLE = 'Включить сбор статистики от Netcat';
const NETCAT_MODULE_STATS_OPENSTAT_ENABLE = 'Включить сбор статистики от Openstat';
const NETCAT_MODULE_STATS_ADMIN_TAB_OPENSTAT_DISABLED = "Сбор статистики от Openstat сейчас отключен. <a href=\"../settings.php?openstat_enable=1\">Включить</a>.";
const NETCAT_MODULE_STATS_ADMIN_TAB_NC_STAT_DISABLED = "Сбор статистики от Netcat сейчас отключен. <a href=\"settings.php?nc_stat_enable=1\">Включить</a>.";

const NETCAT_MODULE_STATS_OPENSTAT_NO_COUNTERS = 'Не создано ни одного счетчика!';
const NETCAT_MODULE_STATS_OPENSTAT_NO_COUNTER_IN_CATALOGUE = 'Для данного сайта не создан счетчик.';
define("NETCAT_MODULE_STATS_OPENSTAT_NO_COUNTERS_IN_TEMPL", "В некоторых макетах дизайна не стоит код счетчика!<br />Вставьте " . htmlspecialchars(NC_OPENSTAT_COUNTER) . " в макеты дизайна вручную, либо нажмите \"<a href=\"?sub_view=templates&DoAction=1&phase=2\">Вставить автоматически во все макеты дизайна</a>\".");

const NETCAT_MODULE_STATS_ADMIN_TAB_OPENSTAT_CATALOGUE = 'Сайт';
const NETCAT_MODULE_STATS_ADMIN_TAB_OPENSTAT_DELETE = 'Удалить';
const NETCAT_MODULE_STATS_ADMIN_TAB_OPENSTAT_EDIT = 'Изменить';
const NETCAT_MODULE_STATS_OPENSTAT_BACK = 'Назад';
const NETCAT_MODULE_STATS_OPENSTAT_INSERT_COUNTER = 'Вставить счетчик.';
const NETCAT_MODULE_STATS_OPENSTAT_ADD_COUNTER = 'Создать счетчик';
const NETCAT_MODULE_STATS_OPENSTAT_ADD_USER_COUNTER = 'У меня уже есть счетчик Openstat.';
const NETCAT_MODULE_STATS_OPENSTAT_ADD_API_COUNTER = 'Я хочу создать новый счетчик Openstat.';
const NETCAT_MODULE_STATS_OPENSTAT_TEMPLATE = 'Макет';
const NETCAT_MODULE_STATS_OPENSTAT_INS_IN_ALL_TEMPLATES = 'Вставить счетчик во все макеты.';
const NETCAT_MODULE_STATS_OPENSTAT_DEL_FROM_ALL_TEMPLATES = 'Удалить счетчик из всех макетов.';

const NETCAT_MODULE_STATS_OPENSTAT_DEL_SELECTED = 'Удалить выбранные';
const NETCAT_MODULE_STATS_OPENSTAT_DEL_ALL = 'Удалить все';
const NETCAT_MODULE_STATS_OPENSTAT_DEL_ALL_CONFIRM = 'Вы уверены, что хотите безвозвратно удалить все счетчики?';
const NETCAT_MODULE_STATS_OPENSTAT_DEL_SELECTED_CONFIRM = 'Вы уверены, что хотите безвозвратно удалить выбранные счетчики?';

const NETCAT_MODULE_STATS_OPENSTAT_YES = 'Да';
const NETCAT_MODULE_STATS_OPENSTAT_NO = 'Нет';

const NETCAT_MODULE_STATS_OPENSTAT_RULES = "Я принимаю условия <a target='_blank' href='https://www.openstat.ru/service/legal/privacy-policy'>Политики конфиденциальности</a> и соглашаюсь с <a target='_blank' href='https://www.openstat.ru/legal/rules'>Правилами пользования услугой</a>, изложенными на веб-сайте Openstat";
const NETCAT_MODULE_STATS_OPENSTAT_ALL_SITES = 'Все сайты';
const NETCAT_MODULE_STATS_OPENSTAT_COMMON_SETTINGS = 'Общие настройки';
const NETCAT_MODULE_STATS_OPENSTAT_DISPLAY_SETTINGS = 'Внешний вид';
const NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR = 'Цвет счетчика';
const NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_0 = '«Прозрачный пиксель» (картинка не выводится)';
const NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_1 = 'Светло-серый';
const NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_2 = 'Темно-серый';
const NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_3 = 'Черный';
const NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_4 = 'Синий';
const NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_5 = 'Голубой';
const NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_6 = 'Темно-зеленый';
const NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_7 = 'Зеленый';
const NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_8 = 'Желтый';
const NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_9 = 'Оранжевый';
const NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_10 = 'Красный';
const NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_11 = 'Розовый';
const NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_12 = 'Бордовый';
const NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_13 = 'Фиолетовый';
const NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_COUNT = '14';
const NETCAT_MODULE_STATS_OPENSTAT_COUNTER_PICTURE_TYPE = 'Тип картинки счётчика (имеет смысл только в том случае, если цвет счетчика не «прозрачный пиксель»)';
const NETCAT_MODULE_STATS_OPENSTAT_COUNTER_PICTURE_TYPE_1 = 'Изображение 88х31 пиксел без индикаторов';
const NETCAT_MODULE_STATS_OPENSTAT_COUNTER_PICTURE_TYPE_2 = 'Изображение 88х31 пиксел с индикаторами';
const NETCAT_MODULE_STATS_OPENSTAT_COUNTER_PICTURE_TYPE_3 = 'Изображение 88х15 пиксел с индикатором';
const NETCAT_MODULE_STATS_OPENSTAT_COUNTER_PICTURE_TYPE_4 = 'Изображение 31х31 пиксел без индикаторов, светло-серый фон';
const NETCAT_MODULE_STATS_OPENSTAT_COUNTER_PICTURE_TYPE_5 = 'Изображение 31х31 пиксел без индикаторов, прозрачный фон';
const NETCAT_MODULE_STATS_OPENSTAT_COUNTER_PICTURE_TYPE_COUNT = '5';
const NETCAT_MODULE_STATS_OPENSTAT_COUNTER_TRACK_LINKS = 'Подсчет уходов';
const NETCAT_MODULE_STATS_OPENSTAT_COUNTER_TRACK_LINKS_NONE = 'Не считать';
const NETCAT_MODULE_STATS_OPENSTAT_COUNTER_TRACK_LINKS_ALL = 'Считать все уходы ';
const NETCAT_MODULE_STATS_OPENSTAT_COUNTER_TRACK_LINKS_EXT = 'Считать только внешние уходы ';
const NETCAT_MODULE_STATS_OPENSTAT_OTHER_SETTINGS = 'Прочие настройки';
const NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COUNTER_RATING = 'Хочу участвовать в рейтингах сайтов Openstat';
const NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COUNTER_ADVERT = 'Сайт является рекламной площадкой';
const NETCAT_MODULE_STATS_OPENSTAT_COUNTER_INSERT_IN_ALL_TEMPLATES_RECOMMENDED = 'Вставить код счетчика во все макеты дизайна (рекомендуется)';
const NETCAT_MODULE_STATS_OPENSTAT_COUNTER_CODE = 'Код счетчика';

const NETCAT_MODULE_STATS_OPENSTAT_ERROR_NO_USER_COUNTER_CODE = 'Вы не ввели код счетчика.';
const NETCAT_MODULE_STATS_OPENSTAT_ERROR_LICENSE_NOT_AGREE = 'Вы не подтвердили свое согласие с правилами. Пользование счетчиками Openstat невозможно.';
const NETCAT_MODULE_STATS_OPENSTAT_ERROR_NO_PRODUCT_NUMBER = 'При установке системы вы не ввели ключ активации. Обратитесь в службу поддержки.';
const NETCAT_MODULE_STATS_OPENSTAT_ERROR_INVALID_PRODUCT_NUMBER = 'При установке системы вы ввели неверный номер лицензии или ключ активации. Обратитесь в службу поддержки.';
const NETCAT_MODULE_STATS_OPENSTAT_ERROR_NO_CONN_WITH_NETCAT = 'Неуспешная попытка соединения с сервером Netcat. Проверьте настройки DNS-клиента или попытайтесь создать счетчик позже. Код ошибки: ';
const NETCAT_MODULE_STATS_OPENSTAT_ERROR_USER_ALREADY_REGISTERED = 'Для данной лицензии уже был зарегистрирован пользователь Openstat. Обратитесь в службу поддержки.';
const NETCAT_MODULE_STATS_OPENSTAT_ERROR_NEW_USER_UNKNOWN_ERROR = 'Произошла ошибка при регистрации пользователя Openstat. Обратитесь в техподдержку. Код ошибки: ';
const NETCAT_MODULE_STATS_OPENSTAT_ERROR_NEW_COUNTER_UNKNOWN_ERROR = 'Ошибка при создании счетчика. Обратитесь в техподдержку. Код ошибки: ';
const NETCAT_MODULE_STATS_OPENSTAT_ERROR_EDIT_COUNTER_UNKNOWN_ERROR = 'Ошибка при изменении параметров счетчика. Обратитесь в техподдержку. Код ошибки: ';
const NETCAT_MODULE_STATS_OPENSTAT_ERROR_COUNTER_AUTH_ERROR = 'Неверные учетные данные пользователя Openstat. Обратитесь в техподдержку.';
const NETCAT_MODULE_STATS_OPENSTAT_ERROR_NEW_CODE_UNKNOWN_ERROR = 'Ошибка при получении кода счетчика. Обратитесь в техподдержку. Код ошибки: ';
const NETCAT_MODULE_STATS_OPENSTAT_ERROR_INVALID_OPENSTAT_COUNTER_ID = 'Счетчик с таким ID на Openstat не зарегистрирован. Обратитесь в техподдержку.';
const NETCAT_MODULE_STATS_OPENSTAT_ERROR_ALREADY_COUNTERS_FOR_ALL_SITES = 'У вас уже созданы счетчики для всех сайтов.';
const NETCAT_MODULE_STATS_OPENSTAT_ERROR_DEL_COUNTER = 'Ошибка при удалении счетчика. Обратитесь в техподдержку. Код ошибки: ';
const NETCAT_MODULE_STATS_OPENSTAT_ERROR_COUNTER_REPORT = 'Ошибка при получении отчета. Обратитесь в техподдержку. Код ошибки: ';
const NETCAT_MODULE_STATS_DB_INSERT_ERR = 'Ошибка добавления данных в БД';

const NETCAT_MODULE_STATS_OPENSTAT_INVALID_COUNTER_ID = 'Счетчика с таким ID не существует!';

const NETCAT_MODULE_STATS_OPENSTAT_SELECT_COUNTER = 'Выберите счетчик';

const NETCAT_MODULE_STATS_OPENSTAT_SEE_STATS_ON_OPENSTAT = 'Смотрите статистику на сайте';
const NETCAT_MODULE_STATS_OPENSTAT_SEE_FULL_STATS_ON_OPENSTAT = 'Смотрите подробную статистику на сайте';

const NETCAT_MODULE_STATS_OPENSTAT_VISITORS = 'Посетители';
const NETCAT_MODULE_STATS_OPENSTAT_SESSIONS = 'Визиты';
const NETCAT_MODULE_STATS_OPENSTAT_PAGEVIEWS = 'Просмотры';
const NETCAT_MODULE_STATS_OPENSTAT_TRANSITIONS = 'Переходы';
const NETCAT_MODULE_STATS_OPENSTAT_PAGE = 'Страница';
const NETCAT_MODULE_STATS_OPENSTAT_TYPE = 'Тип';
const NETCAT_MODULE_STATS_OPENSTAT_PHRASE = 'Фраза';
const NETCAT_MODULE_STATS_OPENSTAT_COUNTRY = 'Страна';
const NETCAT_MODULE_STATS_OPENSTAT_REGION = 'Регион';


const NETCAT_MODULE_STATS_OPENSTAT_TOP_5 = 'топ-5';
const NETCAT_MODULE_STATS_OPENSTAT_SEC = 'сек.';
const NETCAT_MODULE_STATS_OPENSTAT_MIN = 'мин.';
const NETCAT_MODULE_STATS_OPENSTAT_MORE = 'более';

const NETCAT_MODULE_STATS_OPENSTAT_INVALID_START_DATE = 'Неверно введена дата начала отчета.';
const NETCAT_MODULE_STATS_OPENSTAT_INVALID_END_DATE = 'Неверно введена дата окончания отчета.';
const NETCAT_MODULE_STATS_OPENSTAT_INVALID_PERIOD = 'Слишком большой период для такой детализации.';
const NETCAT_MODULE_STATS_OPENSTAT_START_DATE_TOO_BIG = 'Начальная дата должна быть меньше конечной.';

const NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_1 = 'янв.';
const NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_2 = 'фев.';
const NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_3 = 'мар.';
const NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_4 = 'апр.';
const NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_5 = 'май';
const NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_6 = 'июн.';
const NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_7 = 'июл.';
const NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_8 = 'авг.';
const NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_9 = 'сен.';
const NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_10 = 'окт.';
const NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_11 = 'ноя.';
const NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_12 = 'дек.';


const NETCAT_MODULE_STATS_OPENSTAT_LAST_MONTH = 'месяц';
const NETCAT_MODULE_STATS_OPENSTAT_LAST_WEEK = 'неделя';
const NETCAT_MODULE_STATS_OPENSTAT_YESTERDAY = 'вчера';

const NETCAT_MODULE_STATS_OPENSTAT_SUMMARY_STATS = 'Сводная статистика';
const NETCAT_MODULE_STATS_OPENSTAT_SUM_VISITORS = 'Всего посетителей';
const NETCAT_MODULE_STATS_OPENSTAT_SUM_SESSIONS = 'Всего визитов';
const NETCAT_MODULE_STATS_OPENSTAT_SUM_PAGEVIEWS = 'Всего просмотров';
const NETCAT_MODULE_STATS_OPENSTAT_FAILURES_NUM = 'Показатель отказов';
const NETCAT_MODULE_STATS_OPENSTAT_AVERAGE_PAGEVIEWS_PER_SESSION = 'В среднем просмотров за визит';
const NETCAT_MODULE_STATS_OPENSTAT_AVERAGE_TIME_SITE = 'Среднее время на сайте';

const NETCAT_MODULE_STATS_OPENSTAT_PAGES = 'Страницы';
const NETCAT_MODULE_STATS_OPENSTAT_TRAFIC_SOURCES = 'Источники трафика';
const NETCAT_MODULE_STATS_OPENSTAT_TRAFIC_GEOGRAPY = 'География интернет-пользователей';
const NETCAT_MODULE_STATS_OPENSTAT_TRAFIC_GEOGRAPY_BY_COUNTRIES = 'География по странам';
const NETCAT_MODULE_STATS_OPENSTAT_TRAFIC_GEOGRAPY_BY_REGIONS = 'География по регионам';

const NETCAT_MODULE_STATS_OPENSTAT_NO_DATA = 'нет данных';

const NETCAT_MODULE_STATS_OPENSTAT_REDIRECTING_TO = 'Переадресация на';
const NETCAT_MODULE_STATS_OPENSTAT_WAIT_OR_CLICK = 'Дождитесь автоматической переадресации, либо нажмите на кнопку';
const NETCAT_MODULE_STATS_OPENSTAT_GO = 'Перейти';

const NETCAT_MODULE_STATS_OPENSTAT_NOT_FOUND_CURL = 'Расширение cURL не найдено';

// выкинуть!
const NETCAT_MODULE_STATS_OPENSTAT_STATS_PERIOD = 'Статистика по';
const NETCAT_MODULE_STATS_OPENSTAT_STATS_HOUR = 'часам';
const NETCAT_MODULE_STATS_OPENSTAT_STATS_DAY = 'дням';
const NETCAT_MODULE_STATS_OPENSTAT_STATS_WEEK = 'неделям';
const NETCAT_MODULE_STATS_OPENSTAT_STATS_MONTH = 'месяцам';

const NETCAT_MODULE_STATS_OPENSTAT_STATS_FROM = 'с';
const NETCAT_MODULE_STATS_OPENSTAT_STATS_TILL = 'по';
const NETCAT_MODULE_STATS_OPENSTAT_STATS_SHOW = 'Показать';