<?php

const NETCAT_MODULE_FILEMANAGER_DESCRIPTION = 'The module allows you to manage files on the server';

// admin
const NETCAT_MODULE_FILEMANAGER_ADMIN_CURRENT = 'current';
const NETCAT_MODULE_FILEMANAGER_ADMIN_DIR = 'dir';
const NETCAT_MODULE_FILEMANAGER_ADMIN_SIZE = 'size';
const NETCAT_MODULE_FILEMANAGER_ADMIN_PERMISSION = 'permission';
const NETCAT_MODULE_FILEMANAGER_ADMIN_ACTION = 'action';
const NETCAT_MODULE_FILEMANAGER_ADMIN_TOTAL = 'total';
const NETCAT_MODULE_FILEMANAGER_ADMIN_UPLOAD_FILE = 'upload file';
const NETCAT_MODULE_FILEMANAGER_ADMIN_CREATE_DIR = 'create new dir';
const NETCAT_MODULE_FILEMANAGER_ADMIN_DELETE = 'delete';
const NETCAT_MODULE_FILEMANAGER_ADMIN_EDIT = 'edit';
const NETCAT_MODULE_FILEMANAGER_ADMIN_DOWNLOAD = 'download';
const NETCAT_MODULE_FILEMANAGER_ADMIN_SETTINGS = 'settings';
const NETCAT_MODULE_FILEMANAGER_ADMIN_ROOT_LINK = 'begining';

// buttons
const NETCAT_MODULE_FILEMANAGER_ADMIN_SAVE_BUTTON = 'Save';
const NETCAT_MODULE_FILEMANAGER_ADMIN_REWRITE_BUTTON = 'Rewrite';
const NETCAT_MODULE_FILEMANAGER_ADMIN_REFRESH_BUTTON = 'Refresh';
const NETCAT_MODULE_FILEMANAGER_ADMIN_DELETE_BUTTON = 'Delete';
const NETCAT_MODULE_FILEMANAGER_ADMIN_CANCEL_BUTTON = 'Cancel';

// dialogs
const NETCAT_MODULE_FILEMANAGER_ADMIN_DIALOG_DIR_DELETE = 'Delete dir %s?';
const NETCAT_MODULE_FILEMANAGER_ADMIN_DIALOG_FILE_DELETE = 'Delete file %s?';
const NETCAT_MODULE_FILEMANAGER_ADMIN_DIALOG_FILE_REWRITE = 'Rewrite file %s?';

// succesfully
const NETCAT_MODULE_FILEMANAGER_ADMIN_FILE_UPDATED = 'File %s succesfully updated';
const NETCAT_MODULE_FILEMANAGER_ADMIN_FILE_UPLOADED = 'File %s succesfully uploaded';
const NETCAT_MODULE_FILEMANAGER_ADMIN_FILE_REWRITED = 'File %s succesfully rewrited';
const NETCAT_MODULE_FILEMANAGER_ADMIN_FILE_DELETED = 'File %s succesfully deleted';
const NETCAT_MODULE_FILEMANAGER_ADMIN_DIR_CREATED = 'Dir %s succesfully created';
const NETCAT_MODULE_FILEMANAGER_ADMIN_DIR_DELETED = 'Dir %s succesfully deleted';

// other
const NETCAT_MODULE_FILEMANAGER_ADMIN_DIR_V1 = 'dir';
const NETCAT_MODULE_FILEMANAGER_ADMIN_DIR_V2 = 'dirs';
const NETCAT_MODULE_FILEMANAGER_ADMIN_DIR_V3 = 'dirs';
const NETCAT_MODULE_FILEMANAGER_ADMIN_FILE_V1 = 'file';
const NETCAT_MODULE_FILEMANAGER_ADMIN_FILE_V2 = 'files';
const NETCAT_MODULE_FILEMANAGER_ADMIN_FILE_V3 = 'files';

// panel
const NETCAT_MODULE_FILEMANAGER_ADMIN_PANEL_OWNER = 'Owner permissions';
const NETCAT_MODULE_FILEMANAGER_ADMIN_PANEL_GROUP = 'Group permissions';
const NETCAT_MODULE_FILEMANAGER_ADMIN_PANEL_PUBLIC = 'Public permissions';
const NETCAT_MODULE_FILEMANAGER_ADMIN_PANEL_READ = 'read';
const NETCAT_MODULE_FILEMANAGER_ADMIN_PANEL_WRITE = 'write';
const NETCAT_MODULE_FILEMANAGER_ADMIN_PANEL_EXECUTE = 'executable';
const NETCAT_MODULE_FILEMANAGER_ADMIN_PANEL_RENAME = 'Rename';
const NETCAT_MODULE_FILEMANAGER_ADMIN_PANEL_CLOSE = 'Close';
const NETCAT_MODULE_FILEMANAGER_ADMIN_PANEL_SAVE = 'Save';

// errors
const NETCAT_MODULE_FILEMANAGER_ADMIN_ERROR_DIR_NOT_EXIST = 'Dir %s does not exist';
const NETCAT_MODULE_FILEMANAGER_ADMIN_ERROR_DIR_ALREADY_EXIST = 'Dir %s already exist';
const NETCAT_MODULE_FILEMANAGER_ADMIN_ERROR_DIR_WRITE_PERMISSION = 'Insufficient rights to write to the directory %s';
const NETCAT_MODULE_FILEMANAGER_ADMIN_ERROR_DIR_DELETE_PERMISSION = 'Insufficient rights to delete a directory %s';
const NETCAT_MODULE_FILEMANAGER_ADMIN_ERROR_DIR_READ_PERMISSION = 'Insufficient rights to read the directory %s';
const NETCAT_MODULE_FILEMANAGER_ADMIN_ERROR_DIR_CREATE = 'Dir %s write error';
const NETCAT_MODULE_FILEMANAGER_ADMIN_ERROR_FILE_NOT_EXIST = 'File %s does not exist';
const NETCAT_MODULE_FILEMANAGER_ADMIN_ERROR_FILE_WRITE_PERMISSION = 'Insufficient rights to write to the file %s';
const NETCAT_MODULE_FILEMANAGER_ADMIN_ERROR_FILE_DELETE_PERMISSION = 'Insufficient rights to delete a file %s';
const NETCAT_MODULE_FILEMANAGER_ADMIN_ERROR_FILE_READ_PERMISSION = 'Insufficient rights to read a file %s';
const NETCAT_MODULE_FILEMANAGER_ADMIN_ERROR_FILE_WRITE = 'File %s write error';
const NETCAT_MODULE_FILEMANAGER_ADMIN_ERROR_FILE_UPLOAD = 'File %s upload error';
const NETCAT_MODULE_FILEMANAGER_ADMIN_ERROR_NOT_EXIST = 'Object %s does not exist';
const NETCAT_MODULE_FILEMANAGER_ADMIN_ERROR_CHMOD = 'Сan not change the rights to the object %s';
const NETCAT_MODULE_FILEMANAGER_ADMIN_ERROR_UNDEFINED_ACTION = 'This action not available';
const NETCAT_MODULE_FILEMANAGER_ADMIN_ERROR_PATH = 'Invalid value %s';
